### ISSUE TITLE
Skipping Incompatible Libraries

### ISSUE THREAD

**Issue by BioBox** [hissorii/px68k#10]
When attempting to build on Linux, I get "skipping incompatible *.so when searching for -lSDL, etc." or something along those lines, ending with `collect2: error: ld returned 1 exit status`.

Any ideas on how to fix this?

**Comment by hissorii** [comment]
any other errors?
Please write all the errors.

**Comment by BioBox** [comment]
Sorry for the late response. Turns out I was missing some pieces of the toolchain.
This is what I now get when compiling:

```
psp-gcc -I./x11 -I./x68k -I./fmgen -I./win32api -I. -I/usr/psp/sdk/include -G0 -O2 -Wall -I/usr/psp/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -DPX68K_VERSION=0.15 -D_PSP_FW_VERSION=150  -L. -L/usr/psp/sdk/lib   x68k/adpcm.o x68k/bg.o x68k/crtc.o x68k/dmac.o x68k/fdc.o x68k/fdd.o x68k/disk_d88.o x68k/disk_dim.o x68k/disk_xdf.o x68k/gvram.o x68k/ioc.o x68k/irqh.o x68k/mem_wrap.o x68k/mercury.o x68k/mfp.o x68k/palette.o x68k/midi.o x68k/pia.o x68k/rtc.o x68k/sasi.o x68k/scc.o x68k/scsi.o x68k/sram.o x68k/sysport.o x68k/tvram.o x11/joystick.o x11/juliet.o x11/keyboard.o x11/mouse.o x11/prop.o x11/status.o x11/timer.o x11/dswin.o x11/windraw.o x11/winui.o x11/about.o x11/common.o win32api/dosio.o win32api/fake.o win32api/peace.o x68k/d68k.o m68000/c68k.o m68000/m68000.o fmgen/fmgen.o fmgen/fmg_wrap.o fmgen/file.o fmgen/fmtimer.o fmgen/opm.o fmgen/opna.o fmgen/psg.o x11/winx68k.o -lpspgum -lpspgu -lm -lstdc++ -L/usr/psp/lib -lSDLmain -lSDL -lm -L/usr/psp/sdk/lib -L/usr/psp -lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lpsputility -lpspnet_inet -lc -lpspuser -lpspdebug -lpspdisplay -lpspge -lpspctrl -lpspsdk -lc -lpspnet -lpspnet_inet -lpspnet_apctl -lpspnet_resolver -lpsputility -lpspuser -lpspkernel -o px68k.elf
x11/winx68k.o: In function `SDL_main':
(.text+0xd30): undefined reference to `scePowerSetClockFrequency'
collect2: error: ld returned 1 exit status
make: *** [/usr/psp/sdk/lib/build.mak:175: px68k.elf] Error 1
```
`scePowerSetClockFrequency` appears in `psppower.h`, which I have:
`find /usr/psp/sdk/include -name psppower.h` gives it.

**Comment by hissorii** [comment]
You compiled a px68k for the PSP(PlayStation Portable)?
You may have missed the libs for the PSP.
Please check your /usr.psp/lib, /usr/psp/sdk/lib and /usr/psp directories.

**Comment by BioBox** [comment]
Okay, after editing the makefile some more I got it to work, but it seems to expect a file called `psp_logo.png`. Is that supposed to be a part of the SDK or did you forget to include it? It comes up near the end of the makefile.

BTW Yes I'm compiling for PSP. Sorry I didn't mention it.

**Comment by hissorii** [comment]
sorry I forgot to upload psp_logo.png. I could not find it in my PC. 
Please make the png file that size is maybe 144x80.
