### ISSUE TITLE
Android joystick support

### ISSUE THREAD

**Issue by sammargh** [hissorii/px68k#3]
Sorry I only know english but is it possible for joystick support on android?
http://hg.libsdl.org/SDL/rev/24b4e98c6010

**Comment by hissorii** [comment]
I'm going to support joystick for Android when SDL2-2.0.2 will be officially released.

**Comment by hissorii** [comment]
Thank you for long waiting.
Now PX68K for Android Ver0.13 is available, that can handle h/w joystick.

see below
http://hissorii.blog45.fc2.com/blog-entry-251.html
