### ISSUE TITLE
android hardware keys 

### ISSUE THREAD

**Issue by RetroMarioBros** [hissorii/px68k#4]
Is posible ??
Because i have got a Xperia Play

**Comment by hissorii** [comment]
I'll support it.
See issue #3.

**Comment by RetroMarioBros** [comment]
Thanks !!!!

**Comment by hissorii** [comment]
Thank you for long waiting.
Now PX68K for Android Ver0.13 is available, that can handle h/w joystick.

see below
http://hissorii.blog45.fc2.com/blog-entry-251.html

**Comment by RetroMarioBros** [comment]
Ohh!! Thanks but this apk(0.13) found in android 2.3 
Can you fix this?

Date: Tue, 1 Apr 2014 07:12:20 -0700

**Comment by RetroMarioBros** [comment]
Not found in android 2.3 
Sorry but you can fix this? ?
Because i have got xperia play in oficial 2.3 firmware !!
0.11 found in 2.3 but 0.13 not found in 2.3

Date: Tue, 1 Apr 2014 07:12:21 -0700

**Comment by RetroMarioBros** [comment]
Not found in android 2.3 
Sorry but can you fix this? ?
Because i have got xperia play in oficial 2.3 firmware !!
0.11 found in 2.3 but 0.13 not found in 2.3

Date: Tue, 1 Apr 2014 07:12:21 -0700

**Comment by samborambo123** [comment]
Working on nvidia shield in android 4.3. Hat, joystick and button 1/2 work

**Comment by hissorii** [comment]
angelhp, I'm so sorry but px68k ver0.13 needs more than Android 3.1.
This can't be fixed by px68k.
New SDL Library w/ joystick support uses Android API level 12.

Please see below for more information.
http://hg.libsdl.org/SDL/rev/24b4e98c6010

Could you use custom firmware with your device?

**Comment by RetroMarioBros** [comment]
Not i cant use other firmware in my mobile ....it is rhe ultimate oficial firmware ...... And the best performance in this digivice is in this firmware android 2.3
....... In (0.11 version)  found dpad direction!! But not 
Found other buttons !!
Good job !!! Thanks 

Date: Tue, 1 Apr 2014 16:13:41 -0700
