### ISSUE TITLE
Not working on iOS 8.1.2 on iPod Touch 5th Gen

### ISSUE THREAD

**Issue by shadelegend333** [hissorii/px68k#5]
When I open the app, it automatically crashes and goes to the home screen.

This happens with and without the cgrom.dat and iplrom.dat files.

**Comment by hissorii** [comment]
All the letters of both file names are lower-case?

**Comment by shadelegend333** [comment]
Yes, they are lower-case.

**Comment by shadelegend333** [comment]
Never mind. It works now.

**Comment by hissorii** [comment]
Ok, fine.
Could you tell me what's wrong?

**Comment by hissorii** [comment]
I'll close this issue.
