### ISSUE TITLE
Permission to add PX68K to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by inactive123** [hissorii/px68k#9]
Hi there,

We would like to seek your permission to include PX68K as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

Regards,

Daniel De Matteis (Libretro/RetroArch)

**Comment by hissorii** [comment]
OK, please include PX68K in DLC.
I'm very happy about that.

**Comment by inactive123** [comment]
Hi there, thanks a lot!

When we get closer to release, I will contact you again if you'd like to add additional cover art or information to the DLC page.
